# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "panmind-usage-tracker-middleware"
  s.version = "1.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christian Woerner", "Fabrizio Regini", "Marcello Barnaba"]
  s.date = "2012-02-17"
  s.description = "This software collects usage information of a rack-application, assembles a json object and sends this object via UDP to a specified server"
  s.email = "info@panmind.com"
  s.homepage = "http://github.com/Panmind/usage_tracker_middleware"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "a rack middleware that helps to tracks usage"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

